services:
  api_server:
    deploy:
      resources:
        limits:
          cpus: ${API_SERVER_CPU_LIMIT}
          memory: ${API_SERVER_MEM_LIMIT}
        reservations:
          cpus: ${API_SERVER_CPU_RESERVATION}
          memory: ${API_SERVER_MEM_RESERVATION}

  background:
    deploy:
      resources:
        limits:
          cpus: ${BACKGROUND_CPU_LIMIT}
          memory: ${BACKGROUND_MEM_LIMIT}
        reservations:
          cpus: ${BACKGROUND_CPU_RESERVATION}
          memory: ${BACKGROUND_MEM_RESERVATION}

  inference_model_server:
    deploy:
      resources:
        limits:
          cpus: ${INFERENCE_CPU_LIMIT}
          memory: ${INFERENCE_MEM_LIMIT}
        reservations:
          cpus: ${INFERENCE_CPU_RESERVATION}
          memory: ${INFERENCE_MEM_RESERVATION}

  indexing_model_server:
    deploy:
      resources:
        limits:
          cpus: ${INDEXING_CPU_LIMIT}
          memory: ${INDEXING_MEM_LIMIT}
        reservations:
          cpus: ${INDEXING_CPU_RESERVATION}
          memory: ${INDEXING_MEM_RESERVATION}

  relational_db:
    deploy:
      resources:
        limits:
          cpus: ${POSTGRES_CPU_LIMIT}
          memory: ${POSTGRES_MEM_LIMIT}
        reservations:
          cpus: ${POSTGRES_CPU_RESERVATION}
          memory: ${POSTGRES_MEM_RESERVATION}

  index:
    deploy:
      resources:
        limits:
          cpus: ${VESPA_CPU_LIMIT}
          memory: ${VESPA_MEM_LIMIT}
        reservations:
          cpus: ${VESPA_CPU_RESERVATION}
          memory: ${VESPA_MEM_RESERVATION}

  nginx:
    deploy:
      resources:
        limits:
          cpus: ${NGINX_CPU_LIMIT}
          memory: ${NGINX_MEM_LIMIT}
        reservations:
          cpus: ${NGINX_CPU_RESERVATION}
          memory: ${NGINX_MEM_RESERVATION}
