services:
  api_server:
    deploy:
      resources:
        limits:
          cpus: ${API_SERVER_CPU_LIMIT:-1.0}
          memory: ${API_SERVER_MEM_LIMIT:-2g}
        reservations:
          cpus: ${API_SERVER_CPU_RESERVATION:-0.5}
          memory: ${API_SERVER_MEM_RESERVATION:-1g}

  background:
    deploy:
      resources:
        limits:
          cpus: ${BACKGROUND_CPU_LIMIT:-2.0}
          memory: ${BACKGROUND_MEM_LIMIT:-4g}
        reservations:
          cpus: ${BACKGROUND_CPU_RESERVATION:-1.0}
          memory: ${BACKGROUND_MEM_RESERVATION:-2g}

  inference_model_server:
    deploy:
      resources:
        limits:
          cpus: ${INFERENCE_CPU_LIMIT:-2.0}
          memory: ${INFERENCE_MEM_LIMIT:-4g}
        reservations:
          cpus: ${INFERENCE_CPU_RESERVATION:-1.0}
          memory: ${INFERENCE_MEM_RESERVATION:-2g}

  indexing_model_server:
    deploy:
      resources:
        limits:
          cpus: ${INDEXING_CPU_LIMIT:-2.0}
          memory: ${INDEXING_MEM_LIMIT:-4g}
        reservations:
          cpus: ${INDEXING_CPU_RESERVATION:-1.0}
          memory: ${INDEXING_MEM_RESERVATION:-2g}

  relational_db:
    deploy:
      resources:
        limits:
          cpus: ${POSTGRES_CPU_LIMIT:-0.5}
          memory: ${POSTGRES_MEM_LIMIT:-2g}
        reservations:
          cpus: ${POSTGRES_CPU_RESERVATION:-0.25}
          memory: ${POSTGRES_MEM_RESERVATION:-1g}

  index:
    deploy:
      resources:
        limits:
          cpus: ${VESPA_CPU_LIMIT:-6.0}
          memory: ${VESPA_MEM_LIMIT:-12g}
        reservations:
          cpus: ${VESPA_CPU_RESERVATION:-4.0}
          memory: ${VESPA_MEM_RESERVATION:-8g}

  nginx:
    deploy:
      resources:
        limits:
          cpus: ${NGINX_CPU_LIMIT:-0.25}
          memory: ${NGINX_MEM_LIMIT:-128m}
        reservations:
          cpus: ${NGINX_CPU_RESERVATION:-0.1}
          memory: ${NGINX_MEM_RESERVATION:-64m}
